"""add_calificacion_maxima

Revision ID: 09d31047f475
Revises: 3501507bfd1b
Create Date: 2026-04-26 20:42:10.285163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '09d31047f475'
down_revision: Union[str, Sequence[str], None] = '3501507bfd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificacion_maxima', sa.Float(), server_default=sa.text('10.0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.drop_column('calificacion_maxima')

    # ### end Alembic commands ###
