"""empty message

Revision ID: 177d1233526c
Revises: 
Create Date: 2026-02-19 21:54:08.243679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '177d1233526c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrondiseño',
    sa.Column('id_patron', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('diagrama', sa.Text(), nullable=True),
    sa.Column('ventajas', sa.Text(), nullable=False),
    sa.Column('desventajas', sa.Text(), nullable=False),
    sa.Column('pseudocodigo', sa.Text(), nullable=False),
    sa.Column('ejemplos', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_patron')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('contraseñaHash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('administrador',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('docente',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('estudiante',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.usuario_id'], ),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('estudiantegrupo',
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.usuario_id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('estudiante_id', 'grupo_id')
    )
    op.create_table('tarea',
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('fechaInicio', sa.DateTime(), nullable=False),
    sa.Column('fechaFin', sa.DateTime(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.usuario_id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    op.create_table('ejercicio',
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('nivelDificultad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipoEntrada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permiteReintentos', sa.Boolean(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patron_id'], ['patrondiseño.id_patron'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id_tarea'], ),
    sa.PrimaryKeyConstraint('tarea_id')
    )
    op.create_table('estudiantetarea',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.usuario_id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tarea.id_tarea'], ),
    sa.PrimaryKeyConstraint('id_estudiante', 'id_tarea')
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opciones', sa.JSON(), nullable=False),
    sa.Column('respuestaCorrecta', sa.Boolean(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id_tarea'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pruebaevaluacion',
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('fechaInicioPrueba', sa.DateTime(), nullable=False),
    sa.Column('fechaCierre', sa.DateTime(), nullable=False),
    sa.Column('tiempoLimite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id_tarea'], ),
    sa.PrimaryKeyConstraint('tarea_id')
    )
    op.create_table('resoluciontarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaEntrega', sa.DateTime(), nullable=False),
    sa.Column('calificacionTotal', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.usuario_id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id_tarea'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestapregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('retroalimentacion', sa.Text(), nullable=True),
    sa.Column('resolucion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.ForeignKeyConstraint(['resolucion_id'], ['resoluciontarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestapregunta')
    op.drop_table('resoluciontarea')
    op.drop_table('pruebaevaluacion')
    op.drop_table('pregunta')
    op.drop_table('estudiantetarea')
    op.drop_table('ejercicio')
    op.drop_table('tarea')
    op.drop_table('estudiantegrupo')
    op.drop_table('grupos')
    op.drop_table('estudiante')
    op.drop_table('docente')
    op.drop_table('administrador')
    op.drop_table('usuario')
    op.drop_table('patrondiseño')
    # ### end Alembic commands ###
