"""add respuesta_diagrama

Revision ID: 2879814dd674
Revises: d16ce4897b38
Create Date: 2026-04-17 20:41:43.212656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2879814dd674'
down_revision: Union[str, Sequence[str], None] = 'd16ce4897b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestapregunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuesta_diagrama', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestapregunta', schema=None) as batch_op:
        batch_op.drop_column('respuesta_diagrama')

    # ### end Alembic commands ###
