"""add_patron_relacion_table

Revision ID: 3501507bfd1b
Revises: 2879814dd674
Create Date: 2026-04-20 20:03:40.903918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3501507bfd1b'
down_revision: Union[str, Sequence[str], None] = '2879814dd674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patronrelacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_origen_id', sa.Integer(), nullable=False),
    sa.Column('patron_destino_id', sa.Integer(), nullable=False),
    sa.Column('nombre_relacion', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.ForeignKeyConstraint(['patron_destino_id'], ['patrondiseño.id_patron'], ),
    sa.ForeignKeyConstraint(['patron_origen_id'], ['patrondiseño.id_patron'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patronrelacion')
    # ### end Alembic commands ###
